### ISSUE TITLE
NVIDIA GT210 doesn't show output with OC Folder but works with Clover

### ISSUE THREAD

**Issue by deliad2** [iGPU/AMD_OC_Ryzen#1]
Hi

I have 3950x + ASRock X570 Creator

With The clover folder i can see screen with nvidia modded driver on catalina because i set InjectNvidia=true without this flag i can't

What do i have to change in opencore config to make the same as InjectNvidia=True in clover does?

**Comment by aluveitie** [comment]
See there: https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/clover-conversion/Clover-config.md#graphics

**Comment by iGPU** [comment]
OpenCore doesn't seem to need this. I have no builds on X570 on Clover and don't know what you need for it.
