### ISSUE TITLE
AppleALC - config.plist

### ISSUE THREAD

**Issue by ne4u** [iGPU/AMD_OC_Ryzen#10]
alc-layout-id in DeviceProperties, recommended for AppleALC.  layout-id did not work.

UPDATE: Another user reported an issue with sound using this repo and found it ultimately to be a corrupt AppleALC.kext.  At the same time I updated the deviceproperties, I also updated the kext to the newest.  The problem appears to actually be the kext.

**Comment by iGPU** [comment]
"alc-layout-id" is not correct wording. "layout-id" is correct, used in both OpenCore and Clover. I never use on-board sound, so I cannot tell whether good or  bad. I use external USB or TB sound processors.

I'll update kext, but usually comes from Kexts Updater app, or rarely, PAVO's compilation.
