### ISSUE TITLE
GPRW patch prevents AppleHPET from loading

### ISSUE THREAD

**Issue by aluveitie** [iGPU/AMD_OC_Ryzen#11]
I noticed after adding the GPRW patch that AppleHPET is not loading anymore on my system.
As I have a different board (ASRock X570 ITX) I'd be interested if this is also the case on yours?

**Comment by iGPU** [comment]
All these items are offered as options to save people time., but if sleep issues are not a problem, then don't use GPRW. No required for a working build.
