### ISSUE TITLE
I'm having the freezing boot problem but my mobo doesn't have "Above 4G decoding"

### ISSUE THREAD

**Issue by rafnogueira** [iGPU/AMD_OC_Ryzen#12]
So my mobo is a TUF X470 gaming,  my motherboard doesn't have this function on the Bios, Can anyone please help me? 
I'm trying for days and months to make my Hackintosh work again after I upgraded from i5 to a 3900X,  after very much research I can boot only with npci=0x2000 or npci=0x3000 but these flags make the system very unstable, and no matters what I do, video drivers don't boot, I pretty sure after finding some similar cases that is related with "Above 4g decoding", but my motherboard don't have this function in the bios... Please if someone could give me some light or some direction I would be so glad

**Comment by iGPU** [comment]
This is not the site for such problems. Research at AMD-OSX: https://forum.amd-osx.com/index.php?misc/accept-privacy-policy&_xfRedirect=https%3A%2F%2Fforum.amd-osx.com%2F.
