### ISSUE TITLE
Pro Display XDR Possible?

### ISSUE THREAD

**Issue by bleys** [iGPU/AMD_OC_Ryzen#14]
I have this motherboard, an RTX 2080 Ti, and a Pro Display XDR. Do you suspect it's possible to get the Pro Display XDR fully functional on this setup?

**Comment by aluveitie** [comment]
No, RTX cards are not supported by MacOS.

**Comment by bleys** [comment]
That's as I suspected then. Was just curious, as the motherboard has two DisplayPort in ports and full 40Gb/s TB 3 support. I've tried plugging both in to the card and in Windows it doesn't make a difference versus either one of them (it still only connects as a 5K display, so obviously only using one DP stream).

**Comment by iGPU** [comment]
NVidia is supported up through High Sierra (ie, not with Mojave nor Catalina).

**Comment by bleys** [comment]
Do you suspect it would be possible with a Radeon card with dual DisplayPort 1.4 outs?

**Comment by iGPU** [comment]
If you're talking about the Radeon VII, it will work on this mobo, although currently WEG does not always play nicely with Radeon VII cards and you might need to disable WEG.

As for TB, I wouldn't depend on any TB working well unless you can flash firmware; and that probably is not happening with X570s. Best bet is to use a TB AIC (GB TR) with, again, flashed firmware.
