### ISSUE TITLE
OCS Failed to parse real field of type 1 - on boot

### ISSUE THREAD

**Issue by ne4u** [iGPU/AMD_OC_Ryzen#3]
Change:
<.key>HaltLevel<./key>
<.real>2147483648<./real> 

To:
<.key>HaltLevel<./key>
<.integer>2147483648<./integer>

change real to integer

https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/troubleshooting

**Comment by iGPU** [comment]
Sorry about that, I thought I'd fix those. (Some editors don't show them properly.)
