### ISSUE TITLE
Windows fails to boot

### ISSUE THREAD

**Issue by pieter91** [iGPU/AMD_OC_Ryzen#5]
Windows gives a blue screen and ACPI_BIOS_ERROR seconds after booting through OpenCore. 

I understand if you aren't supporting Windows at this point, but if it's an easy fix, I'd be very grateful.

**Comment by iGPU** [comment]
Low priority for me. Better if you boot into WIndows through BIOS. Other option is to research using NdkBootPicker menu system. It adds a switch in ACPI/Quirks (as I recall) that turns off loading all ACPI and kext files. There is a GitHub for it (mentioned at bottom of this repository) and an active thread on InsanelyMac.
