### ISSUE TITLE
Readability / repo organization suggestions

### ISSUE THREAD

**Issue by vade** [iGPU/AMD_OC_Ryzen#7]
Hi

Firstly, *thank you* - this repository is amazing and super helpful. It is sincerely appreciated and its clear a ton of work went into this.

If you're open to it, I have a suggestion or two for readability and ease of use for folks looking to get the most out of their AMD hackintosh with the ASUS x570 Creator board.

The `readme.md` is VERY dense and while it contains a lot of information, the presentation is a bit confusing esp for those not intimately familiar with the nuances.

May I suggest the following repo setup (which I am happy to help with and debug btw).

* Provide 'some predetermined configs' with appropriate EFI/config/ACPI/SSD files.
* Provide detail on variant / custom configs and what to change as per the existing readme.
* Provide deep dive info like in the readme for each component in the repo.

This would provide users with immediately useful config information where each section is pertinent to them.

For example

**Config A**
* ASROCK x570 Creator (Required)
* AMD Ryzen 39XX
* Radeon x5700, x5600, Radeon VII in PCI slot 1
* Internal Bluetooth / WIFI
* Thunderbolt enabled (link to thunderbolt enabled errata with M2 drives)

Provide a folder named "Config A" with EFI and contents pertaining to said build, and appropriate BIOS.

**Config B**
* ASROCK x570 Creator (Required)
* AMD Ryzen 39XX
* Radeon x5700, x5600, Radeon VII in PCI slot 1
* PCI Bluetooth / WIFI 
* Thunderbolt enabled (link to thunderbolt enabled errata with M2 drives)

Provide a folder named "Config B" with EFI and contents pertaining to said build, and appropriate BIOS.

**Config C**
* ASROCK x570 Creator (Required)
* AMD Ryzen 39XX
* Radeon x580
* PCI Bluetooth / WIFI 
* Thunderbolt disabled (link to thunderbolt enabled errata with M2 drives)

Provide a folder named "Config C" with EFI and contents pertaining to said build, and appropriate BIOS.

etc.

Im just now setting up and tuning my X570 Hackintosh and am happy to help troubleshoot. I hope this comes off as constructive, theres a ton of moving parts and it can be intimidating for folks to dive in. If I can help elucidate or clean anything up let me know.

Thank you again.

**Comment by iGPU** [comment]
Good suggestions, but since I no longer have this mobo, I don't wish to spend hours modifying from what is here.

**Comment by vade** [comment]
Mordidly curious - which mobo do you suggest these days for TB3 + 10GBe built in? The Aurous XTreme? Is there a similar repo for that board?

Thanks for all you do for the community!
